#!/usr/bin/env bash

if [ ! -x "$(command -v brightnessctl)" ]; then
  echo 'brightnessctl not found'
  exit 1
fi

PERC=$(brightnessctl -m | grep -oE '[0-9]+%')

if [ -z "$1" ]; then
  echo "$PERC"
  exit 0
fi

SIGN=${1:0:1}
STEP=${1:1}

# Divided by step
MIN=$(($(brightnessctl m)/"$STEP"))

case "$SIGN" in
  "+") brightnessctl set +"$STEP"% &>/dev/null && brightnessctl --save &>/dev/null
    ;;
  "-") brightnessctl --min-value=$MIN set "$STEP"%- &>/dev/null && brightnessctl --save &>/dev/null
    ;;
  *) echo "Bad command format."; exit 1
    ;;
esac

pkill -RTMIN+2 i3blocks
