#!/usr/bin/env bash

PROFILE_PATH=$(find $HOME/.mozilla/firefox -name "*default-release")

EXT=$(cat ""$PROFILE_PATH"/extension-settings.json" | jq '.url_overrides.newTabURL.precedenceList[0]')

if [ "$EXT" != "null" ]; then
  EXT_ENABLED=$(echo "$EXT" | jq '.enabled')

  if [ "$EXT_ENABLED" != "null" ]; then
    EXT_ID=$(echo "$EXT" | jq '.id')
    EXT_UUID=$(cat "$PROFILE_PATH/prefs.js" | grep -oE 'user_pref\(\"extensions.webextensions.uuids.*' | cut -c 45- | sed 's/.\{2\}$//' | jq -r '.' | jq "."$EXT_ID"" | sed -E 's/^\"(.*)\"$/\1/')
    EXT_URL="moz-extension://"$EXT_UUID"/index.html"
  fi
fi

if [ -z "$@" ] && [ ! -z "$EXT_URL" ]; then
  GDK_DPI_SCALE=1.04 /usr/bin/firefox -url "$EXT_URL"
else
  GDK_DPI_SCALE=1.04 /usr/bin/firefox "$@"
fi
