#!/usr/bin/env python3
import sys
import json
from pathlib import Path
import ast

# Usage: firefox-home-extension [extension-name] [profile-path]

try:
  profPath = sys.argv[2]
  with open(f"{profPath}/extensions.json") as file:
    f = json.loads(file.read())["addons"]
    extId = [x for x in f if x["defaultLocale"]["name"] == sys.argv[1]][0]["id"]

  with open(f"{profPath}/prefs.js") as file:
    f = file.readlines()
    uuidsPref = 'user_pref("extensions.webextensions.uuids"'
    extUuids = json.loads(ast.literal_eval([x for x in f if x.startswith(uuidsPref)][0][len(uuidsPref)+2:-3]))

  f = open(f"{Path.home()}/.config/firefox_home_extension", "w")
  f.write(f"moz-extension://{extUuids[extId]}/index.html")
  f.close()
except Exception as e:
  print(e)
  exit(1)
