#!/usr/bin/env python3
import sys
import os
import argparse

script_name=os.path.basename(sys.argv[0])

parser = argparse.ArgumentParser(description="Get code point for an Unicode character")
parser.add_argument("char")
char = parser.parse_args().char

print(char.encode('unicode-escape').decode('ASCII'))
