#!/usr/bin/env bash
# Update file database and suggestions database.

sudo pacman -Fy
sudo pkgfile --update

# Arch repos update and packages upgrade
yay --sudoloop --answerupgrade All --nocleanmenu --nodiffmenu --noconfirm -Syu

### Update fisher
/usr/bin/env fish -c "fisher update"

### Neovim plugins
/usr/bin/nvim -c "PlugUpgrade | PlugUpdate | qa!"

echo "Update completed! Happy fresh hacking! :)"

sleep 3
