#!/usr/bin/env bash

VOL=$(pamixer --get-volume)

if [ -z "$1" ]; then
  echo "$VOL"
  exit 0
fi

if [ "$1" == "toggle" ]; then
  pamixer --toggle-mute
else
  SIGN=${1:0:1}
  STEP="${1#?}"

  case "$SIGN" in
    "+")
      if [[ "$VOL" -lt 150 ]]; then
        pamixer --increase "$STEP" --allow-boost
      fi
      ;;
    "-")
        pamixer --decrease "$STEP" --allow-boost
      ;;
  esac
fi

pkill -RTMIN+1 i3blocks
