#!/usr/bin/env bash

VOL=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

if [ -z "$1" ]; then
  echo "$VOL"
  exit 0
fi

if [ "$1" == "toggle" ]; then
  pactl set-sink-mute 0 toggle
fi

SIGN=${1:0:1}

case "$SIGN" in
  "+")
    if [[ "$VOL" -lt 150 ]]; then
      pactl set-sink-volume 0 $1
    fi
    ;;
  "-")
    pactl set-sink-volume 0 $1
    ;;
esac

pkill -RTMIN+1 i3blocks
